import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:airamp_flutter/src/core/database/database_helper.dart';
import 'package:airamp_flutter/src/core/utils/csv_helper.dart';
import 'package:airamp_flutter/src/features/admin/presentation/web/components/bulk_import_modal.dart';

void main() {
  setUpAll(() {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  });

  group('CsvHelper Tests', () {
    test('parses standard CSV text with varied headers into maps', () {
      const csv = '''
Full Name,Email Address,Role,Grade Level,Section,Student Type,Special Notes
"Dela Cruz, Juan",juan.dc@school.edu,student,Grade 10,"Grade 10 - Emerald",regular,"Top student in science"
Maria Santos,maria.s@school.edu,student,Grade 11,Grade 11 - STEM B,transferee,Transferred from Manila
Sir Robert Lim,robert.lim@deped.gov.ph,teacher,,,regular,Math Faculty
''';

      final result = CsvHelper.parse(csv);
      expect(result.length, 3);

      expect(result[0]['full_name'], 'Dela Cruz, Juan');
      expect(result[0]['email'], 'juan.dc@school.edu');
      expect(result[0]['role'], 'student');
      expect(result[0]['grade'], 'Grade 10');
      expect(result[0]['section'], 'Grade 10 - Emerald');
      expect(result[0]['student_type'], 'regular');
      expect(result[0]['special_notes'], 'Top student in science');

      expect(result[1]['full_name'], 'Maria Santos');
      expect(result[1]['student_type'], 'transferee');

      expect(result[2]['full_name'], 'Sir Robert Lim');
      expect(result[2]['role'], 'teacher');
    });

    test('generates compliant CSV with escaped characters', () {
      final headers = ['Full Name', 'Email', 'Notes'];
      final rows = [
        ['Dela Cruz, Juan', 'juan@test.com', 'Saying "Hello" to all'],
        ['Normal Name', 'normal@test.com', 'Simple note'],
      ];

      final csv = CsvHelper.generate(headers: headers, rows: rows);
      expect(csv, contains('"Dela Cruz, Juan"'));
      expect(csv, contains('"Saying ""Hello"" to all"'));
      expect(csv, contains('normal@test.com,Simple note'));
    });

    test('parses template CSV generated by CsvHelper', () {
      final template = CsvHelper.getStudentTemplateCsv();
      final parsed = CsvHelper.parse(template);
      expect(parsed.isNotEmpty, true);
      expect(parsed.first.containsKey('full_name'), true);
      expect(parsed.first.containsKey('email'), true);
      expect(parsed.first.containsKey('role'), true);
    });
  });

  group('DatabaseHelper Bulk Import Tests', () {
    test('bulkImportUsers inserts users, salts passwords, and reports validation errors', () async {
      final dbHelper = DatabaseHelper();
      final testTime = DateTime.now().millisecondsSinceEpoch;

      final rowsToImport = [
        {
          'full_name': 'Bulk Student One',
          'email': 'bulk.student1_$testTime@school.edu',
          'role': 'student',
          'grade': 'Grade 10',
          'section': 'Grade 10 - Emerald',
          'student_type': 'regular',
        },
        {
          'full_name': 'Bulk Student Two',
          'email': 'bulk.student2_$testTime@school.edu',
          'role': 'student',
          'grade': 'Grade 11',
          'section': 'Grade 11 - STEM B',
          'student_type': 'irregular',
          'special_notes': 'Needs afternoon schedule',
        },
        {
          'full_name': 'Invalid Email Student',
          'email': 'not-an-email',
          'role': 'student',
        },
        {
          'full_name': '',
          'email': 'noname_$testTime@school.edu',
          'role': 'student',
        },
      ];

      final result = await dbHelper.bulkImportUsers(rowsToImport);

      expect(result['total'], 4);
      expect(result['successCount'], 2);
      expect(result['failedCount'], 2);

      final errors = result['errors'] as List;
      expect(errors.length, 2);

      // Verify the imported user is in the database and password is salted
      final db = await dbHelper.database;
      final inserted = await db.query(
        'users',
        where: 'email = ?',
        whereArgs: ['bulk.student1_$testTime@school.edu'],
      );

      expect(inserted.length, 1);
      final user = inserted.first;
      expect(user['full_name'], 'Bulk Student One');
      expect(user['role'], 'student');
      expect(user['section'], 'Grade 10 - Emerald');
      expect(user['password_salt'] != null && (user['password_salt'] as String).isNotEmpty, true);
      // Password must be hashed (not plaintext Student@123)
      expect(user['password'], isNot('Student@123'));
    });
  });

  group('BulkImportModal Widget Tests', () {
    testWidgets('renders modal and switches to Upload CSV tab without overflow', (tester) async {
      tester.view.physicalSize = const Size(1280, 800);
      tester.view.devicePixelRatio = 1.0;
      addTearDown(tester.view.resetPhysicalSize);

      await tester.pumpWidget(
        const ProviderScope(
          child: MaterialApp(
            home: Scaffold(
              body: BulkImportModal(),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // Check title and both tabs exist
      expect(find.text('Bulk Import Students & Faculty'), findsOneWidget);
      expect(find.text('Direct Paste CSV'), findsOneWidget);
      expect(find.text('Upload .CSV File'), findsOneWidget);

      // Tap 'Upload .CSV File' tab
      await tester.tap(find.text('Upload .CSV File'));
      await tester.pumpAndSettle();

      // Ensure 'Browse CSV File' button is rendered and there are NO layout overflow exceptions
      expect(find.text('Browse CSV File'), findsOneWidget);
      expect(tester.takeException(), isNull);
    });
  });
}
